### ISSUE TITLE
Test case 1: Indeksberegning av gjennomsnittlig årsnedbør

### ISSUE THREAD

**Issue by ketilt** [KSSno/KAPy#1]
## Relaterte brukerhistorier
- Som klimaforsker ønsker jeg å beregne egendefinerte klimaindekser basert på biasjusterte klimaframskrivninger fra KSS for å distribuere dette raskt og robust ut til brukerne.
- Som klimaforsker ønsker jeg å beregne ensemble-gjennomsnitt og 30-års midler samtidig som ny klimaindeks beregnes, for å kunne distribuere disse sammen med klimaindeksen.

Kilde: https://github.com/KSSno/Klimakverna-WP1-WP2-WP3b-WP5/issues/11

## Inputfiler
Bruk følgende inputfiler, som er biasjusterte og nedskalerte data fra EURO-CORDEX fra CMIP5 (RCP2.6 & RCP4.5) og CMIP6 (SSP3-7.0):
```
/lustre/storeC-ext/users/kin2100/NVE/EQM/*/pr/[hist,rcp26,rcp45]/*nc4
/lustre/storeC-ext/users/kin2100/NVE/EQM/CMIP6/*/pr/*/*nc4
/lustre/storeC-ext/users/kin2100/MET/3DBC/application/*/pr/[hist,rcp26,rcp45]/*nc4
/lustre/storeC-ext/users/kin2100/MET/3DBC/application/CMIP6/*/pr/*/*nc4
```

## Metode
1. Gjennomsnittlig årsnedbør i periodene 1991–2020, 2041–2070 og 2071–2100, separat for alle modeller og begge biasjusteringsmetodene
2. Ensemblegjennomsnitt av 30-årsverdiene over alle modeller og begge biasjusteringsmetodene
3. Endringsverdi regna ut som relative endringer (i prosent) fra historisk periode til hver av de framtidige periodene

Koordinatboks for Norge: LAT 57.759 til 71.384, LON 4.088 til 31.761

## Output
NetCDF-fil med ensemblegjennomsnitt av 30-årsmiddel endringsverdier for 2041–2070 og 2071–2100

## Test
Resultatet kan sammenliknes med:
https://thredds.met.no/thredds/catalog/KSS/Klima_i_Norge_2100/nyeindekser2015/catalog.html?dataset=KSS/Klima_i_Norge_2100/nyeindekser2015/precMap1x1.nc

**Comment by kajalhb** [comment]
Change in precipitation for model ensembles is found here: `/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/model_ensembles`
@doblerone  Where do I find files to compare the result to? 
For instance, the change for CMIP5 scenario rcp26, `/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/model_ensembles/CMIP5/rcp26/102_rcp26_ensemble_change.nc`

**Comment by doblerone** [comment]
Nice! The corresponding changes are located in 
/lustre/storeC-ext/users/kin2100/MET/annmeans_bc/ensmeans/pr
Files starting with ensemble-mean_change-pr_rcp26_

**Comment by doblerone** [comment]
They look very similar - but not identical. The means should be the same I think (quantiles can deviate).
How do you handle the hadgem_remo and hadgem_rca model? 
They end in 2098, so the End-of-century calculation can be done in several ways.
Where can I find the ensemble mean for the historical period?

**Comment by kajalhb** [comment]
The ensemble means for the historical period are here `/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/model_ensembles/CMIP5/102_CMIP5_historical_statistics.nc` and here `/lustre/storeC-ext/users/klimakverna/development/output/testcase_1/model_ensembles/CMIP6/102_CMIP6_historical_statistics.csv`

For the hadgem_remo and hadgem_rca I didn't do anything special, uses `xclim.ensembles.ensemble_mean_std_max_min()` to calculate statistics, I guess it handles the missing files

**Comment by ketilt** [comment]
@doblerone Any progress on comparing ensemble mean to KiN? As discussed, doesn't have to be exact, just adequate

**Comment by doblerone** [comment]
Yes, the values for rel. precip. changes are similar enough:
RCP2.6:
`cdo infon -selvar,indicator_mean_relative_change 102_rcp26_ensemble_change.nc yields`
   -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
    1 : 0000-00-00 00:00:00       2  1852250 1497802 :     -1.8370      3.0742      8.7286 : indicator_mean_relative_change
    2 : 0000-00-00 00:00:00       3  1852250 1497802 :     -3.9147      1.8622      7.9738 : indicator_mean_relative_change
Corresponding values from KiN:
`cdo infon -mergetime ensemble-mean_change-pr_rcp26_both-bc_rawbc_norway_1km_annual_2041-2070.nc ensemble-mean_change-pr_rcp26_both-bc_rawbc_norway_1km_annual_2071-2100.nc`
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
     1 : 2056-01-01 00:00:00       0  1852250 1497802 :     -1.9223      3.0592      8.6245 : pr            
     2 : 2086-01-01 00:00:00       0  1852250 1497802 :     -4.0247      1.8235      7.6900 : pr

RCP4.5:
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
     1 : 0000-00-00 00:00:00       2  1852250 1497802 :     -3.6210      4.4477      14.614 : indicator_mean_relative_change
     2 : 0000-00-00 00:00:00       3  1852250 1497802 :     -3.7594      5.7989      14.449 : indicator_mean_relative_change
vs.
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
     1 : 2056-01-01 00:00:00       0  1852250 1497802 :     -3.8961      4.2982      14.798 : pr            
     2 : 2086-01-01 00:00:00       0  1852250 1497802 :     -3.7266      5.7087      14.204 : pr    

SSP3-7.0:
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
     1 : 0000-00-00 00:00:00       2  1852250 1497802 :    -0.41078      6.7821      11.760 : indicator_mean_relative_change
     2 : 0000-00-00 00:00:00       3  1852250 1497802 :    -0.61889      11.269      20.771 : indicator_mean_relative_change
vs.     
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
     1 : 2056-01-01 00:00:00       0  1852250 1497802 :    -0.46853      6.7659      11.569 : pr            
     2 : 2086-01-01 00:00:00       0  1852250 1497802 :    -0.82927      11.309      20.976 : pr
